import Theory.CredentialLineageAdmission
import Assurance.CredentialDelegationLineageWitness
#print axioms Minidregg.Theory.CredentialLineageAdmission.capabilityIdFreshCheck_iff
#print axioms Minidregg.Theory.CredentialLineageAdmission.delegationShapeCheck_iff
#print axioms Minidregg.Theory.CredentialLineageAdmission.delegationShapeCheck_refuses_missing_delegate
#print axioms Minidregg.Theory.CredentialLineageAdmission.delegationShapeCheck_refuses_bearer
#print axioms Minidregg.Theory.CredentialLineageAdmission.lineageCheckAux_iff
#print axioms Minidregg.Theory.CredentialLineageAdmission.LineageAnchored.cons
#print axioms Minidregg.Theory.CredentialLineageAdmission.LineageAnchored.parent_exact
#print axioms Minidregg.Theory.CredentialLineageAdmission.LineageAnchored.of_present_reads_preserved
#print axioms Minidregg.Theory.CredentialLineageAdmission.storedLineageCheck_iff
#print axioms Minidregg.Theory.CredentialLineageAdmission.storedLineageCheck_refuses_parent_substitution
#print axioms Minidregg.Theory.CredentialLineageAdmission.storedLineageCheck_congr
#print axioms Minidregg.Assurance.CredentialDelegationLineageWitness.explicit_transfer_accepted
#print axioms Minidregg.Assurance.CredentialDelegationLineageWitness.strict_same_holder_accepted
#print axioms Minidregg.Assurance.CredentialDelegationLineageWitness.unmarked_transfer_refused
#print axioms Minidregg.Assurance.CredentialDelegationLineageWitness.absent_delegation_permission_refused
#print axioms Minidregg.Assurance.CredentialDelegationLineageWitness.bearer_transfer_refused
#print axioms Minidregg.Assurance.CredentialDelegationLineageWitness.substituted_parent_still_well_shaped
#print axioms Minidregg.Assurance.CredentialDelegationLineageWitness.substituted_parent_refused
#print axioms Minidregg.Assurance.CredentialDelegationLineageWitness.orphaned_transfer_refused
#print axioms Minidregg.Assurance.CredentialDelegationLineageWitness.grantor_rotation_keeps_historical_lineage
#print axioms Minidregg.Assurance.CredentialDelegationLineageWitness.mixed_lineage_does_not_imply_root_admission
